import CartProvider from "@/context/CartContext";
import "@/styles/globals.css";

export const metadata = {
  title: "Akbar Portofolio",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }) {
  return (
    <CartProvider>
      <Component {...pageProps} />
    </CartProvider>
  );
}
